apiVersion: v1
kind: Service
metadata:
  name: miniapp-service
  labels:
    app: miniapp
spec:
  selector:
    app: miniapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30500