apiVersion: apps/v1 
kind: Deployment
metadata:
  name: miniweb
spec:
  selector:
    matchLabels:
      app: miniweb
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: miniweb
    spec:
      containers:
      - name: miniapp
        image: ladbam/webcode
        imagePullPolicy: Always
        ports:
        - containerPort: 80
