apiVersion: v1
kind: Service
metadata:
  name: miniweb-service
  labels:
    app: miniweb
spec:
  selector:
    app: miniweb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30555